### ISSUE TITLE
Native linking failed, undefined symbol on targeting iphone

### ISSUE THREAD

**Issue by henriqueu96** [mecvillarina/XFVidyoSample#1]
# Reproduction
- Change the key and the appid
- Change build target to debug | iphone
- Run the project

# Expected Scenario
- App build and run

# Current Scenario
- Native linking failed, undefined symbol on build

# Informations:
SDK Version: 13.2 
Linker behavior: Don't link
Device: IPhone XR
Package version: 1.1.2

**Comment by Muthutc** [comment]
Hi @henriqueu96  I am also facing same issue. 
Did you find out any solution?

**Comment by mecvillarina** [comment]
Hi guys, I got a chance to look on this issue. I released version XFVidyo [1.1.4](https://www.nuget.org/packages/XFVidyo/1.1.4). Please do update the XFVidyo from nuget. 

Also, I have updated the [README](https://github.com/mecvillarina/XFVidyoSample/blob/master/README.md) file for the linker configuration for Vidyo. Let me know if still experiencing this issue.

**Comment by Muthutc** [comment]
Hi @mecvillarina  after Update the Package and added Native Reference I got this error 

__project.iOS/MTOUCH: Error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: "-LNative References" -lcrypto "-LNative References" -lopus "-LNative References" -lspeex "-LNative References" -lsrtp "-LNative References" -lssl "-LNative References" -lVidyoClient (MT5201) (project.iOS)_

_Project.iOS/error MT5209: Error: warning: directory not found for option '-LNative References' (project.iOS) Native linking_

_project.iOS/error MT5209: Error: warning: directory not found for option '-FNative References' (project.iOS) Native linking_

_error MT5209: Error: framework not found VPX (project.iOS) Native linking__

**any Solution?**

**Comment by mecvillarina** [comment]
Hi @Muthutc, It would be possible to share here the content of your iosProject.csproj?

**Comment by Muthutc** [comment]
Hi @mecvillarina  Its working. 
Thanks!
